---

- name: Running playbook to create autoscaling scheduled action
  hosts: localhost
  connection: local

  tasks:

  - name: create a launch config
    ec2_lc:
      region: ap-southeast-2    
      profile: my_boto3_profile      
      name: mike_test_lc
      image_id:  ami-ba3e14d9
      key_name: test-key
      security_groups:  sg-ab5029cf
      instance_type: t2.micro
      assign_public_ip: no
    register: lc

  - debug: msg="{{lc.result.name}}"

  - name: create an autoscaling group
    ec2_asg:
      region: ap-southeast-2    
      profile: my_boto3_profile    
      name: mike_test_asg
      launch_config_name: "{{lc.result.name}}"
      health_check_period: 60
      health_check_type: ELB
      # replace_all_instances: yes
      availability_zones: [ 'ap-southeast-2a', 'ap-southeast-2b', 'ap-southeast-2c' ]
      vpc_zone_identifier: [ 'subnet-616cae05', 'subnet-00ff1676', 'subnet-3d708564' ]
      min_size: 0
      max_size: 0
      desired_capacity: 0
    register: asg

  - debug: msg="{{asg}}"

  - name: create a scheduled action for autoscaling group
    ec2_asg_scheduled_action:
      region: ap-southeast-2    
      profile: my_boto3_profile  
      autoscaling_group_name: mike_test_asg
      scheduled_action_name: mike_test_asg_schedule
      start_time: 2017-06-01T10:00:00Z
      end_time: 2018 August 18 08:00 UTC+10
      recurrence: 40 22 * * 1-5
      min_size: 0
      max_size: 0
      desired_capacity: 0
      state: present
    register: scheduled_action

  - debug: msg="{{scheduled_action}}"